language: node_js
node_js:
- '8'
sudo: required
before_deploy: yarn run build
deploy:
  provider: releases
  api_key:
    secure: TeFDUrWkLIH+QpfCSul4ktHAYcuysCmpqBw3yqkNpUGeNX6ne8VmyO2KnRJCso+RbAarXtlgfRgGv2f6n1qaUy7ZGDhC8qpKj4AzcXzP99wQO2nRHpZDCqfBpBx5L1k++wmnCGfXXaDZCuYhZR+sOs0uW9PBT/P6dWGErRN1b0B4nQUCG+C3X1WXsmjjbBDcJpo6UzsSN1bySx1ueet8afpkoeL3kDHSadZmuKyfmnDok39vpmWd+Hjfd//atJw4KfSfpYSEArhVB1ZLNSAVSaG5E/IMfH2EAdIvH9CNNMPjEa1tC+GubgB4nkKJukw+RHTpmVgy+j+6RD86rCxBii654UrCNGopPIQ9g5jfR868p8dVSPXNTzSM5PCHopV7XV63BET8OdNyKOOzVn3mQkLu91/5Zdv1HWIhgk+uaF3/HebOWm/Y50gB4CQfIdsYfOVKczOtFmMNREt7WMqGv4GSoFU+qfOy5vPD0oL7x9ACu40M1i0sXTIeHss3Q815lI0wH2CWQTe0ZEW0xilyst9zDhpz995H3vIZdEmyGWgmpwoBmNIZSs/7jhXu+YA0oOGforJe5qfuWCTikYAqKXwcYz9LNEdzBAHyVkXLJcOxU8hL5q5ii39IW8B+h5MWOlvjFqAubGLSo0HWsySQ5Y6L89WR3QWzALccPFpL5UQ=
  file: build/*
  skip_cleanup: true
  on:
    tags: true
branches:
  except:
  - gh-pages
cache:
  directories:
  - node_modules
